# Generated by Django 5.2.17 on 2026-09-08 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="slug"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("regulation", "Veille réglementaire"),
                            ("method", "Méthode & bonnes pratiques"),
                            ("product", "Produit"),
                            ("case", "Retour d'expérience"),
                        ],
                        default="regulation",
                        max_length=20,
                        verbose_name="catégorie",
                    ),
                ),
                ("excerpt", models.TextField(max_length=400, verbose_name="chapô")),
                (
                    "body",
                    models.TextField(
                        help_text="HTML simple accepté.", verbose_name="contenu"
                    ),
                ),
                (
                    "published_at",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="publié le",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="en ligne"),
                ),
                (
                    "reading_minutes",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="durée de lecture (min)"
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="nom complet"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="e-mail professionnel"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="téléphone"
                    ),
                ),
                (
                    "organisation",
                    models.CharField(max_length=150, verbose_name="établissement"),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="fonction"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=80, verbose_name="pays"),
                ),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("kontrol", "Fiabilisation des données KYC"),
                            ("vigil", "Profilage clients & transactions"),
                            ("both", "Les deux modules"),
                            ("other", "Autre besoin"),
                        ],
                        default="both",
                        max_length=20,
                        verbose_name="centre d'intérêt",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("demo", "Demande de démonstration"),
                            ("contact", "Contact général"),
                            ("resource", "Téléchargement de ressource"),
                        ],
                        default="demo",
                        max_length=20,
                        verbose_name="origine",
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False,
                        verbose_name="consentement au traitement des données",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="reçu le",
                    ),
                ),
                ("handled", models.BooleanField(default=False, verbose_name="traité")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="notes internes"),
                ),
            ],
            options={
                "verbose_name": "demande entrante",
                "verbose_name_plural": "demandes entrantes",
                "ordering": ["-created_at"],
            },
        ),
    ]
