# Generated by Django 5.2.7 on 2026-09-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="interest",
            field=models.CharField(
                choices=[
                    ("kontrol", "Fiabilisation des données KYC"),
                    ("vigil", "Profilage clients & transactions"),
                    ("both", "Plusieurs modules"),
                    ("other", "Autre besoin"),
                ],
                default="both",
                max_length=20,
                verbose_name="centre d'intérêt",
            ),
        ),
    ]
