// Contenu commercial, repris du site (core/content.py) et resserre pour la diapositive.
const BRAND = {
  name: "Konformix",
  legal: "Konformix SUARL",
  tagline: "La conformité bancaire, industrialisée.",
  city: "Dakar, Sénégal",
  domain: "konformix.com",
  email: "commercial@konformix.com",
  phone: "+221 00 000 00 00",
};

const COMPANY = {
  pitch: "Konformix édite deux logiciels de conformité pour les banques et établissements financiers d'Afrique de l'Ouest. Nous industrialisons deux chantiers que la plupart des établissements de l'UEMOA traitent encore sous Excel : la fiabilisation des dossiers KYC, la surveillance des clients et des transactions.",
  pitch2: "Conçu à Dakar, calibré sur les exigences de la BCEAO et du GIABA, déployé sur l'infrastructure de la banque ou en hébergement souverain régional.",
  founders: [
    { name: "Mamadou Fallou Sylla", role: "Cofondateur — Produit & Conformité",
      bio: "Praticien de la conformité et du contrôle permanent en banque, concepteur de la première plateforme de notation de la fiabilité des données KYC." },
    { name: "Mansour Diop", role: "Cofondateur — Technologie & Opérations",
      bio: "Architecture logicielle, déploiements chez les établissements clients et sécurité de la plateforme." },
  ],
  stats: [
    { v: "161", l: "établissements de crédit agréés dans l'UEMOA à fin 2025", s: "BCEAO" },
    { v: "3", l: "nouvelles instructions BCEAO LBC/FT en vigueur depuis le 18 mars 2025", s: "Instructions n°001 à 003-03-2025" },
    { v: "8", l: "pays couverts par un cadre réglementaire unique", s: "Loi uniforme UEMOA, 31 mars 2023" },
  ],
  pains: [
    { i: "TbId", t: "Des dossiers KYC incomplets",
      d: "Pièces expirées, professions non renseignées, bénéficiaires effectifs absents. Personne ne sait chiffrer le taux de complétude." },
    { i: "TbCopy", t: "Des doublons clients invisibles",
      d: "Le même client existe sous trois identités dans le core banking : risque sous-évalué et seuils contournés sans intention." },
    { i: "TbAlertTriangle", t: "Des alertes ingérables",
      d: "Un paramétrage par seuils fixes produit des milliers d'alertes par mois, dont plus de 95 % de faux positifs." },
    { i: "TbClipboardCheck", t: "Des contrôles non traçables",
      d: "Le contrôle permanent s'exécute dans des classeurs non versionnés. À l'inspection, la preuve devient un exercice périlleux." },
  ],
  chart: {
    title: "Le superviseur a changé de comportement en 2025",
    cats: ["Injonctions", "Blâmes", "Avertissements", "Sanctions pécuniaires"],
    y2024: [20, 14, 6, 16],
    y2025: [40, 30, 6, 35],
    note: "Mesures prononcées par la Commission Bancaire de l'UMOA à l'encontre des établissements assujettis. Les injonctions ont doublé en un an, les sanctions pécuniaires ont progressé de 118 %.",
    motifs: "Motifs récurrents : dispositif LBC/FT non conforme, contrôle interne défaillant, gouvernance insuffisante.",
  },
  audiences: [
    { i: "TbShieldCheck", r: "Directeur de la Conformité / RCCI",
      d: "Démontrer au superviseur et au conseil que le dispositif LBC/FT est effectif, mesuré et documenté." },
    { i: "TbClipboardCheck", r: "Responsable du Contrôle Permanent",
      d: "Exécuter et tracer les contrôles de second niveau sans reconstruire un classeur à chaque campagne." },
    { i: "TbChartPie", r: "Directeur des Risques",
      d: "Disposer d'une cartographie des risques clients alimentée par des données à jour, pas par une enquête annuelle." },
    { i: "TbServer", r: "Directeur des Systèmes d'Information",
      d: "Ajouter une brique de conformité sans refonte du core banking, avec une intégration par fichiers ou API." },
  ],
  diffs: [
    { i: "TbScale", t: "Calibré sur la réglementation UEMOA",
      d: "Référentiels livrés pré-paramétrés sur les instructions BCEAO de mars 2025 et la loi uniforme de 2023, pas une réglementation européenne adaptée après coup." },
    { i: "TbCoins", t: "Un coût aligné sur les budgets locaux",
      d: "Nous vendons en FCFA, avec un déploiement initial mesuré en semaines quand les projets internationaux se comptent en mois." },
    { i: "TbLock", t: "Vos données restent chez vous",
      d: "Déploiement sur l'infrastructure de la banque ou en hébergement souverain régional. Aucune donnée client ne quitte le périmètre défini." },
    { i: "TbUsers", t: "Une équipe qui a fait le métier",
      d: "Konformix est fondée par des praticiens du contrôle permanent et de la conformité bancaire en Afrique de l'Ouest." },
  ],
  steps: [
    { n: "01", t: "Diagnostic de fiabilité", d: "2 semaines",
      x: "Mesure du taux de complétude réel sur un échantillon du référentiel, et chiffrage des anomalies." },
    { n: "02", t: "Pilote cadré", d: "6 à 8 semaines",
      x: "Déploiement sur un segment de clientèle ou un réseau d'agences, avec des objectifs chiffrés convenus à l'avance." },
    { n: "03", t: "Généralisation", d: "3 mois",
      x: "Extension à l'ensemble du référentiel, intégration au core banking, formation des équipes conformité." },
    { n: "04", t: "Exploitation et veille", d: "en continu",
      x: "Mise à jour des référentiels réglementaires, ajout de scénarios, revue trimestrielle avec la direction." },
  ],
};

const FAQ = {
  core: { q: "Faut-il remplacer notre core banking ?",
    a: "Non. Konformix se connecte en lecture à votre référentiel existant, par extraction de fichiers ou par API. Aucune modification de votre système de production n'est nécessaire pour démarrer." },
  data: { q: "Où sont hébergées les données ?",
    a: "Au choix : sur votre propre infrastructure, ou dans un centre de données de la région. Nous n'exportons jamais de données clients hors du périmètre que vous définissez." },
  delay: { q: "Combien de temps avant les premiers résultats ?",
    a: "Le diagnostic de fiabilité produit des chiffres exploitables en deux semaines. Un pilote complet est opérationnel en six à huit semaines." },
  explain: { q: "Le moteur d'alerte est-il explicable ?",
    a: "Oui, et c'est un choix structurant. Chaque alerte affiche la règle ou le scénario qui l'a déclenchée et les valeurs en cause. Aucune décision ne repose sur un modèle indéfendable devant un inspecteur." },
  intl: { q: "Comment vous situez-vous face aux solutions internationales ?",
    a: "Elles couvrent un périmètre plus large et conviennent aux grands groupes disposant d'une équipe projet dédiée. Nous nous adressons aux établissements qui veulent un dispositif effectif rapidement, à un coût cohérent avec un bilan de la zone." },
  support: { q: "Proposez-vous un accompagnement au-delà du logiciel ?",
    a: "Oui : cadrage du dispositif, rédaction des procédures, formation des équipes et préparation aux missions d'inspection font partie de nos prestations." },
};

const PRODUCTS = {
  kontrol: {
    key: "kontrol",
    name: "Konformix Kontrol",
    icon: "TbShieldCheck",
    kicker: "Fiabilisation et notation des données KYC",
    summary: "Mesure en continu la qualité du référentiel client, détecte les anomalies et pilote les campagnes de régularisation jusqu'à leur clôture.",
    outcome: "Passer d'un taux de complétude inconnu à un indicateur suivi mensuellement.",
    features: [
      { i: "TbGauge", t: "Score de fiabilité par dossier",
        d: "Une note de 0 à 100 par client, fondée sur des règles paramétrables : complétude, validité, cohérence, fraîcheur." },
      { i: "TbAdjustmentsHorizontal", t: "Moteur de règles sans code",
        d: "Le responsable conformité crée et teste ses règles depuis l'interface, sans passer par la DSI. Chaque règle est versionnée." },
      { i: "TbCopy", t: "Détection de doublons",
        d: "Rapprochement approximatif adapté aux graphies ouest-africaines : variantes de noms et translittérations arabes." },
      { i: "TbTarget", t: "Campagnes de régularisation",
        d: "Anomalies affectées aux agences ou aux chargés de clientèle, avec échéance, relance et suivi du taux de traitement." },
      { i: "TbChartBar", t: "Tableau de bord direction",
        d: "Évolution du score global, classement des agences, top des anomalies. Exportable pour le comité des risques." },
      { i: "TbHistory", t: "Piste d'audit complète",
        d: "Qui a modifié quelle règle, quand, et quel dossier a été régularisé par qui. Au format attendu par l'inspection." },
    ],
    // Diapositive propre au produit
    zoom: {
      title: "Le score de fiabilité, en cinq indicateurs",
      intro: "Un score défendable devant un inspecteur se construit sur des mesures simples, calculées à chaque rafraîchissement du référentiel.",
      items: [
        { n: "01", t: "Complétude", d: "Champs obligatoires réellement renseignés" },
        { n: "02", t: "Validité", d: "Pièces d'identité en cours de validité" },
        { n: "03", t: "Cohérence", d: "Accord entre champs d'un même dossier" },
        { n: "04", t: "Fraîcheur", d: "Date de dernière mise à jour du dossier" },
        { n: "05", t: "Unicité", d: "Absence de doublon sur le même client" },
      ],
    },
    gains: [
      { i: "TbReportAnalytics", t: "Un chiffre, pas une impression",
        d: "Le taux de complétude devient un indicateur mensuel présentable au comité des risques et au superviseur." },
      { i: "TbTarget", t: "Une remédiation pilotée",
        d: "Les anomalies sont affectées, échéancées et suivies par entité : la régularisation avance au lieu de s'empiler." },
      { i: "TbCertificate", t: "Une preuve prête pour l'inspection",
        d: "Chaque contrôle et chaque correction sont horodatés et exportables, sans reconstitution a posteriori." },
    ],
    faq: ["core", "data", "delay"],
    closing: "Envoyez-nous un extrait anonymisé de votre référentiel client. Sous deux semaines, nous vous remettons une évaluation chiffrée de sa fiabilité, sans engagement de votre part.",
  },
  vigil: {
    key: "vigil",
    name: "Konformix Vigil",
    icon: "TbRadar",
    kicker: "Profilage des clients et surveillance des transactions",
    summary: "Classe les clients par niveau de risque, apprend leur comportement normal et n'alerte que sur les écarts qui méritent un examen humain.",
    outcome: "Réduire le volume d'alertes tout en augmentant le taux de déclarations de soupçon pertinentes.",
    features: [
      { i: "TbUserShield", t: "Scoring de risque client",
        d: "Notation multi-critères — pays, activité, canal, statut PPE, structure de détention — avec pondérations ajustables." },
      { i: "TbActivityHeartbeat", t: "Profils comportementaux",
        d: "Chaque client dispose d'un profil transactionnel de référence. L'alerte se déclenche sur l'écart au profil." },
      { i: "TbWorld", t: "Scénarios typologiques",
        d: "Bibliothèque calibrée sur les typologies GIABA : fractionnement, comptes de passage, flux transfrontaliers atypiques." },
      { i: "TbListCheck", t: "Filtrage des listes",
        d: "Criblage contre les listes de sanctions, les gels d'avoirs nationaux et les bases PPE, avec gestion des homonymies." },
      { i: "TbFileSearch", t: "Gestion du cycle d'alerte",
        d: "File priorisée, affectation, investigation documentée et génération du projet de déclaration pour la CENTIF." },
      { i: "TbRadar", t: "Réduction des faux positifs",
        d: "Le moteur apprend des décisions de clôture et réordonne les alertes, sans jamais en supprimer automatiquement." },
    ],
    zoom: {
      title: "Du seuil fixe au profil comportemental",
      intro: "Un seuil unique appliqué à une clientèle hétérogène produit du bruit et manque les vrais signaux.",
      before: { t: "Paramétrage par seuils fixes", items: [
        "Un même seuil pour le commerçant et le salarié",
        "Des milliers d'alertes par mois, plus de 95 % de faux positifs",
        "L'équipe traite le volume, pas le risque",
        "Aucune mémoire des décisions passées",
      ] },
      after: { t: "Profil comportemental Konformix Vigil", items: [
        "Un profil de référence par client, construit sur son historique",
        "L'alerte porte sur l'écart au profil, motif affiché",
        "File priorisée : les analystes traitent d'abord le risque",
        "Le moteur apprend des clôtures, sans rien supprimer",
      ] },
    },
    gains: [
      { i: "TbSearch", t: "Moins de bruit, plus de signal",
        d: "La priorisation par écart au profil réduit le volume à traiter et remonte les dossiers qui méritent l'examen." },
      { i: "TbFileSearch", t: "Une investigation documentée",
        d: "Chaque alerte porte son motif, ses valeurs et sa décision : le projet de déclaration à la CENTIF part d'un dossier constitué." },
      { i: "TbCertificate", t: "Un dispositif explicable",
        d: "Aucune décision ne repose sur un modèle opaque. Chaque alerte se justifie règle en main devant un inspecteur." },
    ],
    faq: ["explain", "data", "delay"],
    closing: "Confiez-nous un extrait anonymisé de vos flux et de votre référentiel. Sous deux semaines, nous mesurons le bruit de votre paramétrage actuel et ce qu'un profilage comportemental y changerait.",
  },
};

module.exports = { BRAND, COMPANY, FAQ, PRODUCTS };
